---
- name: Get swap file status
  ansible.builtin.stat:
    path: "{{ swapfile_path }}"
  register: swapfile_status

- name: Set initial facts
  ansible.builtin.set_fact:
    recreate_swapfile: false

- name: Set the existing_swapfile_size fact
  ansible.builtin.set_fact:
    existing_swapfile_size: "{{ (swapfile_status.stat.size / 1024 / 1024) | int }}"
  when: swapfile_status.stat.exists

- name: Set the recreate_swapfile fact
  ansible.builtin.set_fact:
    recreate_swapfile: "{{ (swapfile_size | replace('M', '')) != existing_swapfile_size }}"
  when: swapfile_status.stat.exists

- name: Check swap file condition
  ansible.builtin.include_tasks: check-condition.yml

- name: Create or modify swap file
  when: not swapfile_status.stat.exists or recreate_swapfile or swapfile_condition.stdout == 'swapfile disabled'
  block:
    - name: Disable swap file
      ansible.builtin.include_tasks: disable.yml
      when: recreate_swapfile

    - name: Create swap file
      community.general.filesize:
        source: /dev/zero
        path: "{{ swapfile_path }}"
        size: "{{ swapfile_size }}"
        blocksize: "{{ swapfile_block_size }}"
        owner: root
        group: root
        mode: "600"

    - name: Setup swap file
      ansible.builtin.command: mkswap {{ swapfile_path }}
      register: setup_swapfile
      changed_when: setup_swapfile.changed

    - name: Add swap file to /etc/fstab
      ansible.builtin.include_tasks: manage-fstab.yml

    - name: Enable swap file
      ansible.builtin.command: swapon {{ swapfile_path }}
      register: enable_swapfile
      changed_when: enable_swapfile.changed
