---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

provisioner:
  name: ansible
  env:
    ANSIBLE_PYTHON_INTERPRETER: auto_silent
    ANSIBLE_LIBRARY: $ANSIBLE_LIBRARY:$VIRTUAL_ENV/lib/$PYTHON_VERSION/site-packages/molecule_plugins/vagrant/modules

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: debian-13
    box: fernandobohrer/debian-13
    cpus: 2
    memory: 2048

  - name: ubuntu-2404
    box: bento/ubuntu-24.04 # https://developer.hashicorp.com/vagrant/docs/boxes#official-boxes
    cpus: 2
    memory: 2048
